#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Build frame-aligned subtask, memory and optional RECAP-style labels for G1."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np

from openpi.training import g1_training


def _read_records(path: Path | None, key: str) -> list[dict[str, Any]]:
    if path is None:
        return []
    if path.suffix == ".jsonl":
        return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict):
        payload = payload.get(key, payload.get("records", []))
    if not isinstance(payload, list):
        raise ValueError(f"{path} must contain a list of JSON records")
    return [dict(row) for row in payload]


def _bool_or_none(value: Any) -> bool | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in {"", "none", "null", "unknown"}:
        return None
    if normalized in {"1", "true", "yes", "y", "success"}:
        return True
    if normalized in {"0", "false", "no", "n", "failure", "failed"}:
        return False
    raise ValueError(f"Cannot parse success boolean: {value!r}")


def _annotation_index(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    for row in rows:
        key = row.get("source_episode_id", row.get("episode_id", row.get("episode_index")))
        if key is None:
            raise ValueError("Each episode annotation must contain source_episode_id, episode_id, or episode_index")
        key = str(key)
        if key in index:
            raise ValueError(f"Duplicate episode annotation: {key}")
        segments = sorted(row.get("segments", []), key=lambda segment: int(segment.get("start_frame", 0)))
        previous_end = -1
        for segment in segments:
            start = int(segment.get("start_frame", 0))
            end = int(segment.get("end_frame", start))
            if start < 0 or end < start or start <= previous_end:
                raise ValueError(f"Episode {key} has a negative, reversed, or overlapping segment: {segment}")
            previous_end = end
        index[key] = {**row, "segments": segments}
    return index


def _intervention_at(episode: dict[str, Any], frame: int, intervals: list[dict[str, Any]]) -> bool:
    episode_index = str(episode["episode_index"])
    source_id = str(episode["source_episode_id"])
    for interval in intervals:
        target = interval.get("source_episode_id", interval.get("episode_id", interval.get("episode_index")))
        if target is None or str(target) not in {episode_index, source_id}:
            continue
        start = int(interval.get("start_frame", interval.get("start_index", 0)))
        end = int(interval.get("end_frame", interval.get("end_index", start)))
        if start <= frame <= end:
            return True
    return False


def _segment_at(annotation: dict[str, Any], frame: int) -> dict[str, Any]:
    for segment in annotation.get("segments", []):
        start = int(segment.get("start_frame", 0))
        end = int(segment.get("end_frame", start))
        if start <= frame <= end:
            return dict(segment)
    return {}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--episode-map",
        required=True,
        type=Path,
        help="meta/g1_episode_map.json generated by the LeRobot converter",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--annotations", type=Path, help="Manually labelled success/subtask/memory JSON or JSONL")
    parser.add_argument(
        "--interventions", type=Path, help="Manually labelled intervention frame ranges in JSON or JSONL"
    )
    args = parser.parse_args()

    mapping = json.loads(args.episode_map.read_text(encoding="utf-8"))
    episodes = mapping.get("episodes", mapping)
    if not isinstance(episodes, list):
        raise ValueError("Episode map must contain an episodes list")
    episode_indices = [int(episode["episode_index"]) for episode in episodes]
    source_ids = [str(episode["source_episode_id"]) for episode in episodes]
    if len(set(episode_indices)) != len(episode_indices) or len(set(source_ids)) != len(source_ids):
        raise ValueError("episode_index and source_episode_id values in the episode map must be unique")
    annotations = _annotation_index(_read_records(args.annotations, "episodes"))
    interventions = _read_records(args.interventions, "intervals")
    valid_episode_keys = set(source_ids) | {str(index) for index in episode_indices}
    unknown_annotations = sorted(set(annotations) - valid_episode_keys)
    if unknown_annotations:
        raise ValueError(f"Annotations reference unknown episodes: {unknown_annotations}")
    for interval in interventions:
        target = interval.get("source_episode_id", interval.get("episode_id", interval.get("episode_index")))
        start = int(interval.get("start_frame", interval.get("start_index", 0)))
        end = int(interval.get("end_frame", interval.get("end_index", start)))
        if target is None or str(target) not in valid_episode_keys:
            raise ValueError(f"Intervention references an unknown episode: {target!r}")
        if start < 0 or end < start:
            raise ValueError(f"Invalid intervention frame range: {interval}")

    records: list[dict[str, Any]] = []
    for episode in episodes:
        source_id = str(episode["source_episode_id"])
        episode_index = int(episode["episode_index"])
        num_steps = int(episode["num_steps"])
        if episode_index < 0 or num_steps <= 0:
            raise ValueError(f"Invalid episode-map record: {episode}")
        annotation = annotations.get(source_id, annotations.get(str(episode_index), {}))
        merged = {**episode, **annotation}
        success = _bool_or_none(merged.get("success"))
        for frame in range(num_steps):
            frame_labels = {**merged, **_segment_at(annotation, frame)}
            is_intervention = _intervention_at(episode, frame, interventions)
            advantage = 1.0 if success is True and not is_intervention else (-1.0 if success is False else 0.0)
            rl_token_weight = float(frame_labels.get("rl_token_weight", 1.0))
            if not np.isfinite(rl_token_weight) or rl_token_weight < 0:
                raise ValueError("rl_token_weight must be finite and non-negative")
            record = {
                "episode_index": episode_index,
                "frame_index": frame,
                "advantage_indicator": advantage,
                "use_advantage": success is not None,
                "is_human_intervention": is_intervention,
                "rl_token_weight": rl_token_weight,
                "memory": str(frame_labels.get("memory", "")),
                "next_memory": str(frame_labels.get("next_memory", "")),
            }
            if frame_labels.get("subtask"):
                record["subtask"] = str(frame_labels["subtask"])
            records.append(record)

    g1_training.write_jsonl(records, args.output)
    print(f"wrote {len(records)} frame-aligned sidecar rows to {args.output}")


if __name__ == "__main__":
    main()
